apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    app: api-gateway
  name: apigatewaysvc
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    nodePort: 30040
  selector:
    app: api-gateway

