apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    app: authenticationservice
  name: authenticationservicesvc
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8091
  selector:
    app: authenticationservice

