apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    
  labels:
    app: configserver
  name: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      containers:
      - env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eurekaserversvc:8761/eureka
        image: shwetashukla23/configserver:latest
        name: config-server-container
        ports:
        - containerPort: 8888
      restartPolicy: Always

