apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    app: configserver
  name: configserversvc
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    app: configserver

