apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    app: emailservice
  name: emailservicesvc
spec:
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    app: emailservice

