apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    app: eurekaserver
  name: eurekaserversvc
spec:
  type: NodePort
  ports:
  - name: "8761"
    port: 8761
    nodePort: 30041
  selector:
    app: eurekaserver

