apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    app: mongodbservice
  name: mongodbservicesvc
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    app: mongodbservice

