apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    app: mysqlservice
  name: mysqlservicesvc
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    app: mysqlservice

