apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    
  labels:
    app: paymentservice
  name: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eurekaserversvc:8761/eureka
        image: shwetashukla23/paymentservice:latest
        name: payment-service-container
        ports:
        - containerPort: 8089
      restartPolicy: Always

