apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    app: paymentservice
  name: paymentservicesvc
spec:
  ports:
  - name: "8089"
    port: 8089
    targetPort: 8089
  selector:
    app: paymentservice

