apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    app: product-webapp
  name: productwebappsvc
spec:
  ports:
  - name: "8087"
    port: 8087
    targetPort: 8087
  selector:
    app: product-webapp

