apiVersion: v1
kind: Service
metadata:
  annotations:
    
  labels:
    app: userservice
  name: userservicesvc
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    app: userservice

